clear all; close all;
a0=1;
a1=1;
b=9;
% u0=5; t0=0; du=0;
% u0=0; t0=0; du=1;
u0=0; t0=1; du=1;
k=2;
% f1=figure; grid on; hold on;
% f2=figure; grid on; hold on;
f3=figure; grid on; hold on;
% f4=figure; grid on; hold on;
% f5=figure; grid on; hold on;
% f6=figure; grid on; hold on;
f7=figure; grid on; hold on;
% f8=figure; grid on; hold on;

t1=0:0.1:10;
xw=0*t1+45;
lam=-1;
% figure(f5);
% A1=0;
% xs1=A1.*exp(lam*t1);
% x1=xs1+xw;
% plot(t1, xs1, t1, xw, t1, x1, 'r');
% legend('xs', 'xw', 'x');
% title('Analityczna pochodna od x(0)=0');
% figure(f6);
% A2=-4;
% xs2=A2.*exp(lam*t1);
% x2=xs2+xw;
% plot(t1, xs2, t1, xw, t1, x2, 'g');
% legend('xs', 'xw', 'x');
% title('Analityczna pochodna od x(0)=4');
figure(f7);
A3=-45;
xs3=A3.*exp(lam*t1);
x3=xs3+xw;
plot(t1, xs3, t1, xw, t1, x3, 'b');
legend('xs', 'xw', 'x');
title('Analityczna x(0)=0');
% figure(f8);
% A4=-42;
% xs4=A4.*exp(lam*t1);
% x4=xs4+xw;
% plot(t1, xs4, t1, xw, t1, x4, 'm');
% legend('xs', 'xw', 'x');
% title('Analityczna x(0)=3');

% x0=45;
% sim('simulink1');
% figure(f1);
% plot(t, x, 'r');
% legend('x');
% title('Simulink pochodna od x(0)=0');
% x0=41;
% sim('simulink1');
% figure(f2);
% plot(t, x, 'g');
% legend('x');
% title('Simulink pochodna od x(0)=4');
x0=0;
sim('simulink1');
figure(f3);
plot(t, x, 'b');
legend('x');
title('Simulink x(0)=0');
% x0=3;
% sim('simulink1');
% figure(f4);
% plot(t, x, 'm');
% legend('x');
% title('Simulink x(0)=3');